### ISSUE TITLE
Can we have the same versions of the theme on GitHub and NPM?

### ISSUE THREAD

**Issue by mabasic** [narative/gatsby-theme-novela#234] opened 2019-12-18 16:23 UTC
Sorry to bring this up again, but every time I try to update to the latest version I see a miss match of versions on NPM and GitHub...

On NPM it says 0.10.5 is the latest, on GitHub it says 0.11.2 is the latest and that 0.10.5 does not even exist. 0.10.4 exists on Github, but does not exist on NPM.

Is there a way to have both to be the same?

**Comment by brotzky** [comment] 2019-12-18 19:05
Yes, sorry. We have an automated script that's broken right now. It's supposed to handle releases but isn't deploying properly. JP is currently on holiday and wants to fix it when he returns. In the meantime i'm manually deploying locally and sometimes forget. Ill do one now :)

**Comment by aleccool213** [comment] 2020-01-14 14:14
You should consider using https://github.com/semantic-release/semantic-release

**Comment by brotzky** [comment] 2020-01-14 17:42
Ah really cool. Did you want to set it up @aleccool213 ?

**Comment by aleccool213** [comment] 2020-01-14 17:47
Sure thing

**Comment by jpvalery** [comment] 2020-01-18 15:31
@aleccool213 we evaluated semantic-release and it just doesn't work with monorepos like this one. 

Duplicate of #242 - Closing.

**Closed by jpvalery** 2020-01-18 15:31 UTC
Labels: bug, duplicate

**Comment by aleccool213** [comment] 2020-01-18 18:00
@jpvalery good to know 👍

**Comment by brotzky** [comment] 2020-01-18 23:33
Thanks @jpvalery :)
