### ISSUE TITLE
Multiple Authors for a single Post

### ISSUE THREAD

**Issue by brotzky** [narative/gatsby-theme-novela#19] opened 2019-08-05 17:35 UTC

**Comment by brotzky** [comment] 2019-08-07 01:12
@johnletey 

Multiple authors for a single post is now supported
https://github.com/narative/gatsby-theme-novela/commit/caf64880f8b89c63c6b4385a50d15a4d3e012408

Will be in next release.

**Comment by johnletey** [comment] 2019-08-07 09:04
Thank you so much @brotzky!

**Comment by johnletey** [comment] 2019-08-07 10:35
@brotzky There seems to be a weird thing going on with the avatars of the multiple authors! It seems as though the avatars are becoming square and then going back to circle. I've attached a recording:

![Kapture 2019-08-07 at 11 32 48](https://user-images.githubusercontent.com/30328854/62616433-644a2080-b907-11e9-933d-bbd9a764b4c9.gif)

**Comment by brotzky** [comment] 2019-08-07 16:03
Really strange! Going to check it out. Safari with the curve balls again.

**Comment by johnletey** [comment] 2019-08-07 16:03
Thanks so much!

**Comment by brotzky** [comment] 2019-08-07 16:05
@johnletey I can't seem to reproduce it on safari. Really strange bug.

Safari tests:
http://d.ntve.co/8Wu6XV

**Comment by johnletey** [comment] 2019-08-07 16:09
The screen recording doesn't seem to be loading ... but that is weird that you can't reproduce ... I'll ask my colleague on the project to see if he can reproduce (as he uses Safari)

**Comment by brotzky** [comment] 2019-08-07 16:13
@johnletey embedded the gif

**Comment by johnletey** [comment] 2019-08-07 16:15
Thanks @brotzky ... still super weird ... wonder what's happening on my computer

**Comment by nikitavoloboev** [comment] 2019-08-07 16:16
I can reproduce this as well and it shows like what @johnletey has. 

When you hover over the thing it will jump from circle to square to circle and back.

![recording](https://user-images.githubusercontent.com/6391776/62639292-25cc5a00-b937-11e9-9635-4ebfa813e1e1.gif)

**Comment by brotzky** [comment] 2019-08-07 16:34
Hoping v0.0.9 fixes this issue. I had to guess at the possible issue as I can't seem to reproduce it on my side.

**Comment by johnletey** [comment] 2019-08-07 16:36
Yes @brotzky ... just noticed that this is fixed in the new version!

**Closed** 2019-08-07 16:40 UTC
Labels: enhancement
