### ISSUE TITLE
"Multiple versions of Emotion detected"

### ISSUE THREAD

**Issue by dennismorello** [narative/gatsby-theme-novela#110] opened 2019-08-31 08:42 UTC
**Version of Novela you are using**
0.5.1

**Number of posts you have and which data source**
Local, 2 posts

**Describe the bug**
When starting the dev server or opening the prod version, the browser logs the following warning: 

> Multiple versions of Emotion detected, and theming might not work as expected. Please ensure there is only one copy of @emotion/core installed in your application.

**To Reproduce**
1. Start the dev server or build the prod version
2. Run your web browser and open the site
3. Open the dev console
4. See the warning

**Expected behavior**
Only a single instance of Emotion should be loaded.

**Screenshots**
See additional context section.

**Browser**
 - All browsers

**Additional context**
Complete warning stacktrace:

> Multiple versions of Emotion detected, and theming might not work as expected. Please ensure there is only one copy of @emotion/core installed in your application. 
>     in ThemeProvider (at Layout.tsx:36)
>     in Layout (at article.template.tsx:82)
>     in Article (created by HotExportedArticle)
>     in HotExportedArticle (created by PageRenderer)
>     in PageRenderer (at json-store.js:93)
>     in JSONStore (at root.js:51)
>     in RouteHandler (at root.js:73)
>     in EnsureResources (at root.js:61)
>     in LocationHandler (at root.js:119)
>     in LocationProvider (created by Context.Consumer)
>     in Context.Consumer (created by Location)
>     in Location (at root.js:118)
>     in Root (at root.js:126)

**Comment by alfieqashwa** [comment] 2019-09-01 09:35
I see the messages while deploy on Netlify

![multiple emotion detected](https://user-images.githubusercontent.com/15263927/64074442-7a17ef00-ccd5-11e9-8c54-6f38926fb894.png)

Probably it affect to random fontsize in the code when using mobile browser ?

I see this on @slorber site https://sebastienlorber.com/handling-api-request-race-conditions-in-react 
![IMG_3454](https://user-images.githubusercontent.com/15263927/64074519-7f296e00-ccd6-11e9-8478-0f93463e5bff.PNG)

**Comment by slorber** [comment] 2019-09-03 13:47
Hi

I'm sorry @alfieqashwa but I don't understand what you mean. I checked my site and run yarn build and didn't have any such warning. Don't understand either what your screenshots mean

**Comment by alfieqashwa** [comment] 2019-09-04 05:32
Hello Mr @slorber. The screenshot was taken from mobile browser (mobile chrome) showing that there is different font size in the code (pre) when open your blog https://sebastienlorber.com/handling-api-request-race-conditions-in-react from mobile browser. Also on my blog https://www.alfieqashwa.me/cool-site-using-gatsby-theme-novela. I checked too from official gatsby-theme-novela (without shadowing, version 0.5.1).

if you write long code on the same line like this:
```javascript
var sOne, sTwo = "JavaScript syntax highlighting", "Long string to check the view from the mobile browser";
alert(s);
```
then the font-size will get bigger on the mobile browser.  it's just a small bug but i'm curious. I see on kentcdodds.com that is not happening.

**Comment by slorber** [comment] 2019-09-05 08:23
thanks didn't notice that ;)

I'd rather have a smaller font when code is large

**Comment by alfieqashwa** [comment] 2019-09-05 12:38
@slorber but how to reduce the font-size when it automatically gets bigger on mobile browser when we write long code on one line? do you have clue in where to modify?

**Comment by slorber** [comment] 2019-09-05 15:01
i don't know, it just makes sense to do that imo ;)

**Comment by brotzky** [comment] 2019-09-14 16:12
Are people still seeing this? I'm unable to reproduce and would like to close this issue if it's gone.

**Comment by alfieqashwa** [comment] 2019-09-16 06:59
So far, I don't see it anymore after updated to version 0.6.5. Thank you @brotzky

**Closed** 2019-09-16 16:07 UTC
